services:
  db:
    image: postgres:15
    container_name: ols-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chethai_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

  be:
    build:
      context: ./be
    container_name: ols-be
    environment:
      DATABASE_URL: "postgresql://postgres:root@db:5432/chethai_db?schema=public"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy

  fe:
    build:
      context: ./fe
    container_name: ols-fe
    ports:
      - "5173:5173"
    depends_on:
      - be
